version: "3.8"

services:
  localdjango:
    # build: .
    image: localdjango
    ports:
      - "8000:8000"
    volumes:
      - ./app:/home/app
    command: python3 manage.py runserver 0.0.0.0:8000


  